export type LanguageLink = { label: string; href: string };

export type Article = {
  slug: string;
  title: string;
  kicker: string;
  summary: string;
  minutes: number;
  next?: { href: string; label: string };
  video?: { href: string; label: string };
  audio?: { href: string; label: string };
  languages?: LanguageLink[];
};

export const readingPath: Article[] = [
  {
    slug: "the-true-gospel-and-the-false",
    title: "The True Gospel and the False",
    kicker: "01 — Begin here",
    summary:
      "Two gospels are preached today: one man-centered, and one God-centered. This article draws the line clearly.",
    minutes: 12,
    next: { href: "/the-gospel-message", label: "The Gospel Message" },
    languages: [
      { label: "Afrikaans", href: "https://afrikaans.cfcindia.com/article/the-true-gospel-and-the-false-10" },
      { label: "Albanian", href: "https://albanian.cfcindia.com/article/the-true-gospel-and-the-false-16" },
      { label: "Amharic", href: "https://amharic.cfcindia.com/am/article/the-true-gospel-and-the-false" },
      { label: "Armenian", href: "https://armenian.cfcindia.com/article/the-true-gospel-and-the-false-17" },
      { label: "Bengali", href: "https://bengali.cfcindia.com/article/the-true-gospel-and-the-false-14" },
      { label: "Bosnian", href: "https://bosnian.cfcindia.com/article/the-true-gospel-and-the-false-18" },
      { label: "Bulgarian", href: "https://bulgarian.cfcindia.com/article/the-true-gospel-and-the-false-19" },
      { label: "Chinese (Simplified)", href: "https://chinese-simplified.cfcindia.com/zh-si/article/the-true-gospel-and-the-false" },
      { label: "Chinese (Traditional)", href: "https://chinese-traditional.cfcindia.com/zh-tr/article/the-true-gospel-and-the-false" },
      { label: "Czech", href: "https://cestina.cfcindia.com/cs/article/the-true-gospel-and-the-false" },
      { label: "Croatian", href: "https://croatian.cfcindia.com/article/the-true-gospel-and-the-false-11" },
      { label: "Dutch", href: "https://nederlands.cfcindia.com/nl/article/the-true-gospel-and-the-false" },
      { label: "Finnish", href: "https://suomi.cfcindia.com/fi/article/the-true-gospel-and-the-false" },
      { label: "French", href: "https://francais.cfcindia.com/article/the-true-gospel-and-the-false-5" },
      { label: "German", href: "https://deutsch.cfcindia.com/de/article/the-true-gospel-and-the-false" },
      { label: "Greek", href: "https://greek.cfcindia.com/article/the-true-gospel-and-the-false-12" },
      { label: "Hindi", href: "https://hindi.cfcindia.com/hi/article/the-true-gospel-and-the-false" },
      { label: "Hungarian", href: "https://hungarian.cfcindia.com/hu/article/the-true-gospel-and-the-false" },
      { label: "Indonesian", href: "https://indonesian.cfcindia.com/id/article/the-true-gospel-and-the-false" },
      { label: "Italian", href: "https://italiano.cfcindia.com/it/article/the-true-gospel-and-the-false" },
      { label: "Kannada", href: "https://kannada.cfcindia.com/article/the-true-gospel-and-the-false-0" },
      { label: "Korean", href: "https://korean.cfcindia.com/article/the-true-gospel-and-the-false-15" },
      { label: "Macedonian", href: "https://macedonian.cfcindia.com/article/the-true-gospel-and-the-false-22" },
      { label: "Malagasy", href: "https://malagasy.cfcindia.com/mg/article/the-true-gospel-and-the-false" },
      { label: "Malayalam", href: "https://malayalam.cfcindia.com/ml/article/the-true-gospel-and-the-false" },
      { label: "Marathi", href: "https://marathi.cfcindia.com/mr/article/the-true-gospel-and-the-false" },
      { label: "Montenegrin", href: "https://montenegrin.cfcindia.com/article/the-true-gospel-and-the-false-23" },
      { label: "Norwegian", href: "https://www.cfcindia.org/resources/en/gospel/the-true-gospel-and-the-false-norwegian.pdf" },
      { label: "Polish", href: "https://polski.cfcindia.com/article/the-true-gospel-and-the-false-8" },
      { label: "Portuguese", href: "https://portugues.cfcindia.com/pt/article/the-true-gospel-and-the-false" },
      { label: "Romanian", href: "https://romanian.cfcindia.com/article/the-true-gospel-and-the-false-6" },
      { label: "Russian", href: "https://russian.cfcindia.com/ru/article/the-true-gospel-and-the-false" },
      { label: "Serbian", href: "https://serbian.cfcindia.com/sr/article/the-true-gospel-and-the-false" },
      { label: "Slovenian", href: "https://slovenian.cfcindia.com/article/the-true-gospel-and-the-false-20" },
      { label: "Spanish", href: "https://espanol.cfcindia.com/es/article/true-and-false-gospel" },
      { label: "Swedish", href: "https://swedish.cfcindia.com/article/the-true-gospel-and-the-false-13" },
      { label: "Tamil", href: "https://tamil.cfcindia.com/ta/article/the-true-gospel-and-the-false" },
      { label: "Telugu", href: "https://telugu.cfcindia.com/article/the-true-gospel-and-the-false-4" },
      { label: "Tigrinya", href: "https://tigrinya.cfcindia.com/article/the-true-gospel-and-false" },
      { label: "Urdu", href: "https://urdu.cfcindia.com/ur/article/the-true-gospel-and-the-false" },
    ],
  },
  {
    slug: "the-gospel-message",
    title: "The Gospel Message",
    kicker: "02 — Be born again",
    summary:
      "What it means to be saved: repentance toward God, faith in the Lord Jesus Christ, and a new beginning.",
    minutes: 28,
    next: { href: "/counterfeit-revival", label: "Counterfeit Revival" },
    video: { href: "https://www.youtube.com/watch?v=f4vbFQ6gCfc", label: "Watch on YouTube" },
    audio: {
      href: "https://www.cfcindia.com/sermon/a-clear-gospel-message",
      label: "Listen / download audio",
    },
    languages: [
      { label: "Afrikaans", href: "https://afrikaans.cfcindia.com/article/a-clear-gospel-message-13" },
      { label: "Albanian", href: "https://albanian.cfcindia.com/article/a-clear-gospel-message-19" },
      { label: "Amharic", href: "https://www.cfcindia.org/resources/en/gospel/a-clear-gospel-message-amharic.pdf" },
      { label: "Armenian", href: "https://armenian.cfcindia.com/article/a-clear-gospel-message-20" },
      { label: "Bengali", href: "https://bengali.cfcindia.com/article/a-clear-gospel-message-16" },
      { label: "Bosnian", href: "https://bosnian.cfcindia.com/article/a-clear-gospel-message-21" },
      { label: "Bulgarian", href: "https://bulgarian.cfcindia.com/article/a-clear-gospel-message-22" },
      { label: "Chinese (Simplified)", href: "https://chinese-simplified.cfcindia.com/zh-si/article/a-clear-gospel-message" },
      { label: "Chinese (Traditional)", href: "https://chinese-traditional.cfcindia.com/zh-tr/article/a-clear-gospel-message" },
      { label: "Czech", href: "https://cestina.cfcindia.com/cs/article/a-clear-gospel-message" },
      { label: "Croatian", href: "https://www.cfcindia.org/resources/en/gospel/a-clear-gospel-message-croatian.pdf" },
      { label: "Dutch", href: "https://nederlands.cfcindia.com/article/a-clear-gospel-message-9" },
      { label: "Finnish", href: "https://suomi.cfcindia.com/fi/article/a-clear-gospel-message" },
      { label: "French", href: "https://francais.cfcindia.com/article/a-clear-gospel-message-5" },
      { label: "German", href: "https://deutsch.cfcindia.com/de/article/a-clear-gospel-message" },
      { label: "Greek", href: "https://greek.cfcindia.com/article/a-clear-gospel-message-14" },
      { label: "Gujarati", href: "https://gujarati.cfcindia.com/article/a-clear-gospel-message-17" },
      { label: "Hebrew", href: "https://www.cfcindia.org/resources/en/gospel/a-clear-gospel-message-hebrew.pdf" },
      { label: "Hindi", href: "https://hindi.cfcindia.com/hi/article/a-clear-gospel-message" },
      { label: "Hungarian", href: "https://hungarian.cfcindia.com/hu/article/a-clear-gospel-message" },
      { label: "Italian", href: "https://italiano.cfcindia.com/it/article/a-clear-gospel-message" },
      { label: "Kannada", href: "https://kannada.cfcindia.com/article/a-clear-gospel-message-0" },
      { label: "Korean", href: "https://korean.cfcindia.com/article/a-clear-gospel-message-18" },
      { label: "Macedonian", href: "https://macedonian.cfcindia.com/article/a-clear-gospel-message-25" },
      { label: "Malagasy", href: "https://malagasy.cfcindia.com/mg/article/a-clear-gospel-message" },
      { label: "Malayalam", href: "https://malayalam.cfcindia.com/ml/article/a-clear-gospel-message" },
      { label: "Marathi", href: "https://marathi.cfcindia.com/mr/article/a-clear-gospel-message" },
      { label: "Montenegrin", href: "https://montenegrin.cfcindia.com/article/a-clear-gospel-message-26" },
      { label: "Norwegian", href: "https://www.cfcindia.org/resources/en/gospel/a-clear-gospel-message-norwegian.pdf" },
      { label: "Polish", href: "https://polski.cfcindia.com/article/a-clear-gospel-message-8" },
      { label: "Portuguese", href: "https://portugues.cfcindia.com/pt/article/a-clear-gospel-message" },
      { label: "Romanian", href: "https://romanian.cfcindia.com/article/a-clear-gospel-message-6" },
      { label: "Russian", href: "https://russian.cfcindia.com/ru/article/a-clear-gospel-message" },
      { label: "Serbian", href: "https://serbian.cfcindia.com/article/a-clear-gospel-message-11" },
      { label: "Slovenian", href: "https://slovenian.cfcindia.com/article/a-clear-gospel-message-23" },
      { label: "Spanish", href: "https://espanol.cfcindia.com/es/article/a-clear-gospel-message" },
      { label: "Swedish", href: "https://swedish.cfcindia.com/article/a-clear-gospel-message-15" },
      { label: "Tamil", href: "https://tamil.cfcindia.com/ta/article/a-clear-gospel-message" },
      { label: "Telugu", href: "https://telugu.cfcindia.com/article/a-clear-gospel-message-4" },
      { label: "Tigrinya", href: "https://tigrinya.cfcindia.com/ti/article/a-clear-gospel-message" },
      { label: "Urdu", href: "https://urdu.cfcindia.com/article/a-clear-gospel-message-12" },
    ],
  },
  {
    slug: "counterfeit-revival",
    title: "Counterfeit Revival",
    kicker: "03 — Discernment",
    summary:
      "Why so many are deceived by false prophets and counterfeit revivals — and how to build an unshakeable church.",
    minutes: 10,
    next: { href: "/the-video-tape-of-our-memory", label: "The Video Tape of Our Memory" },
    languages: [
      { label: "Afrikaans", href: "https://afrikaans.cfcindia.com/article/counterfeit-revival-12" },
      { label: "Albanian", href: "https://albanian.cfcindia.com/article/counterfeit-revival-15" },
      { label: "Amharic", href: "https://amharic.cfcindia.com/am/article/counterfeit-revival" },
      { label: "Armenian", href: "https://armenian.cfcindia.com/article/counterfeit-revival-16" },
      { label: "Bosnian", href: "https://bosnian.cfcindia.com/article/counterfeit-revival-17" },
      { label: "Bulgarian", href: "https://bulgarian.cfcindia.com/article/counterfeit-revival-18" },
      { label: "Chinese (Traditional)", href: "https://chinese-traditional.cfcindia.com/zh-tr/article/counterfeit-revival" },
      { label: "Czech", href: "https://cestina.cfcindia.com/cs/article/counterfeit-revival" },
      { label: "Croatian", href: "https://croatian.cfcindia.com/article/counterfeit-revival-19" },
      { label: "Dutch", href: "https://nederlands.cfcindia.com/nl/article/counterfeit-revival" },
      { label: "Finnish", href: "https://suomi.cfcindia.com/fi/article/counterfeit-revival" },
      { label: "French", href: "https://francais.cfcindia.com/article/counterfeit-revival-4" },
      { label: "German", href: "https://deutsch.cfcindia.com/de/article/counterfeit-revival" },
      { label: "Greek", href: "https://greek.cfcindia.com/article/counterfeit-revival-13" },
      { label: "Hindi", href: "https://hindi.cfcindia.com/hi/article/counterfeit-revival" },
      { label: "Hungarian", href: "https://hungarian.cfcindia.com/hu/article/counterfeit-revival" },
      { label: "Italian", href: "https://italiano.cfcindia.com/it/article/counterfeit-revival" },
      { label: "Kannada", href: "https://kannada.cfcindia.com/article/counterfeit-revival-0" },
      { label: "Macedonian", href: "https://macedonian.cfcindia.com/article/counterfeit-revival-21" },
      { label: "Malagasy", href: "https://malagasy.cfcindia.com/mg/article/counterfeit-revival" },
      { label: "Marathi", href: "https://marathi.cfcindia.com/mr/article/counterfeit-revival" },
      { label: "Montenegrin", href: "https://montenegrin.cfcindia.com/article/counterfeit-revival-22" },
      { label: "Norwegian", href: "https://www.cfcindia.org/resources/en/gospel/counterfeit-revival-norwegian.pdf" },
      { label: "Polish", href: "https://polski.cfcindia.com/article/counterfeit-revival-7" },
      { label: "Portuguese", href: "https://portugues.cfcindia.com/pt/article/counterfeit-revival" },
      { label: "Romanian", href: "https://romanian.cfcindia.com/article/counterfeit-revival-5" },
      { label: "Russian", href: "https://russian.cfcindia.com/ru/article/counterfeit-revival" },
      { label: "Serbian", href: "https://serbian.cfcindia.com/sr/article/counterfeit-revival" },
      { label: "Sinhala", href: "https://sinhala.cfcindia.com/si/article/deception-and-counterfeit-revival" },
      { label: "Slovenian", href: "https://slovenian.cfcindia.com/article/counterfeit-revival-20" },
      { label: "Spanish", href: "https://espanol.cfcindia.com/es/article/counterfeit-revival" },
      { label: "Swedish", href: "https://swedish.cfcindia.com/article/counterfeit-revival-14" },
      { label: "Tamil", href: "https://tamil.cfcindia.com/ta/article/counterfeit-revival" },
      { label: "Telugu", href: "https://telugu.cfcindia.com/article/counterfeit-revival-3" },
      { label: "Urdu", href: "https://urdu.cfcindia.com/ur/article/counterfeit-revival" },
    ],
  },
  {
    slug: "the-video-tape-of-our-memory",
    title: "The Video Tape of Our Memory",
    kicker: "04 — The judgment",
    summary:
      "A coming day of account, the record written in every memory, and the only way the tape can be erased.",
    minutes: 8,
    next: { href: "/basic-christian-teachings", label: "Basic Christian Teachings" },
    languages: [
      { label: "Albanian", href: "https://albanian.cfcindia.com/article/the-video-tape-of-our-memory-8" },
      { label: "Armenian", href: "https://armenian.cfcindia.com/article/the-video-tape-of-our-memory-9" },
      { label: "Bosnian", href: "https://bosnian.cfcindia.com/article/the-video-tape-of-our-memory-10" },
      { label: "Bulgarian", href: "https://bulgarian.cfcindia.com/article/the-video-tape-of-our-memory-11" },
      { label: "Czech", href: "https://cestina.cfcindia.com/cs/article/the-video-tape-of-our-memory" },
      { label: "Croatian", href: "https://croatian.cfcindia.com/article/the-video-tape-of-our-memory-12" },
      { label: "Dutch", href: "https://nederlands.cfcindia.com/nl/article/the-video-tape-of-our-memory" },
      { label: "French", href: "https://francais.cfcindia.com/article/the-video-tape-of-our-memory-4" },
      { label: "German", href: "https://deutsch.cfcindia.com/de/article/the-video-tape-of-our-memory" },
      { label: "Hindi", href: "https://hindi.cfcindia.com/hi/article/the-video-tape-of-our-memory" },
      { label: "Hungarian", href: "https://hungarian.cfcindia.com/hu/article/the-video-tape-of-our-memory" },
      { label: "Italian", href: "https://italiano.cfcindia.com/it/article/the-video-tape-of-our-memory" },
      { label: "Kannada", href: "https://kannada.cfcindia.com/article/the-video-tape-of-our-memory-0" },
      { label: "Macedonian", href: "https://macedonian.cfcindia.com/article/the-video-tape-of-our-memory-14" },
      { label: "Malagasy", href: "https://malagasy.cfcindia.com/mg/article/the-video-tape-of-our-memory" },
      { label: "Malayalam", href: "https://malayalam.cfcindia.com/ml/article/the-video-tape-of-our-memory" },
      { label: "Marathi", href: "https://marathi.cfcindia.com/mr/article/the-video-tape-of-our-memory" },
      { label: "Montenegrin", href: "https://montenegrin.cfcindia.com/article/the-video-tape-of-our-memory-15" },
      { label: "Portuguese", href: "https://portugues.cfcindia.com/pt/article/the-video-tape-of-our-memory" },
      { label: "Romanian", href: "https://romanian.cfcindia.com/ro/article/the-video-tape-of-our-memory" },
      { label: "Serbian", href: "https://serbian.cfcindia.com/sr/article/the-video-tape-of-our-memory" },
      { label: "Sinhala", href: "https://sinhala.cfcindia.com/si/article/the-video-tape-of-our-memory" },
      { label: "Slovenian", href: "https://slovenian.cfcindia.com/article/the-video-tape-of-our-memory-13" },
      { label: "Spanish", href: "https://espanol.cfcindia.com/es/article/the-video-tape-of-our-memory" },
      { label: "Tamil", href: "https://tamil.cfcindia.com/ta/article/the-video-tape-of-your-memory" },
      { label: "Telugu", href: "https://telugu.cfcindia.com/article/the-video-tape-of-our-memory-3" },
      { label: "Urdu", href: "https://urdu.cfcindia.com/ur/article/the-video-tape-of-our-memory" },
    ],
  },
];

export function getArticle(slug: string) {
  return readingPath.find((article) => article.slug === slug);
}
