export type Teaching = {
  n: number;
  title: string;
  href: string;
  duration?: string;
};

const basic = (slug: string) =>
  `https://www.cfcindia.com/basic-christian-teachings/${slug}`;

const bible = (slug: string) => `https://www.cfcindia.com/through-the-bible/${slug}`;

export const basicTeachings: Teaching[] = [
  { n: 1, title: "The Origin Of Evil", href: basic("01-the-origin-of-evil") },
  { n: 2, title: "God Makes Evil Work For Good", href: basic("02-god-makes-evil-work-for-good") },
  { n: 3, title: "The Power Of Choice", href: basic("03-the-power-of-choice") },
  { n: 4, title: "Sin Comes From Unbelief", href: basic("04-sin-comes-from-unbelief") },
  { n: 5, title: "The Function Of The Conscience", href: basic("05-the-function-of-conscience") },
  { n: 6, title: "Why Christ Had To Die", href: basic("06-why-christ-has-to-die") },
  { n: 7, title: "Repentance", href: basic("07-repentance") },
  { n: 8, title: "Faith", href: basic("08-faith") },
  { n: 9, title: "The Gift Of The Holy Spirit", href: basic("09-the-gift-of-the-holy-spirit") },
  { n: 10, title: "God’s Word Is Our Food", href: basic("10-gods-word-is-our-food") },
  { n: 11, title: "God’s Word Helps Us Overcome Satan", href: basic("11-gods-word-helps-us-overcome-satan") },
  { n: 12, title: "God’s Word Renews Our Mind", href: basic("12-gods-word-renews-our-mind") },
  { n: 13, title: "Religiosity And Spirituality", href: basic("13-religiosity-and-spirituality") },
  { n: 14, title: "Maximum Or Minimum For The Lord", href: basic("14-maximum-or-minimum-for-the-lord") },
  { n: 15, title: "A Son Or A Servant", href: basic("15-a-son-or-a-servant") },
  { n: 16, title: "Keeping The Tenth Commandment", href: basic("16-keeping-the-tenth-commandment") },
  { n: 17, title: "Dead Works", href: basic("17-dead-works") },
  { n: 18, title: "More On Dead Works", href: basic("18-more-on-dead-works") },
  { n: 19, title: "Some More On Dead Works", href: basic("19-some-more-on-dead-works") },
  { n: 20, title: "Still More On Dead Works", href: basic("20-still-more-on-dead-works") },
  { n: 21, title: "Law And Grace", href: basic("21-law-and-grace-0") },
  { n: 22, title: "One Reason For Failure", href: basic("22-one-reason-for-failure") },
  { n: 23, title: "Another Reason For Failure", href: basic("23-another-reason-for-failure") },
  { n: 24, title: "More Reasons For Failure", href: basic("24-more-reasons-for-failure") },
  { n: 25, title: "Faith And Praise", href: basic("25-faith-and-praise") },
  { n: 26, title: "Crucifixion And Praise", href: basic("26-crucifixion-and-praise") },
  { n: 27, title: "Praise Drives Satan Out", href: basic("27-praise-drives-satan-out") },
  { n: 28, title: "The New Song Of Praise", href: basic("28-the-new-song-of-praise") },
  { n: 29, title: "Praise Brings Deliverance", href: basic("29-praise-brings-deliverance") },
  { n: 30, title: "Praise Opens Closed Doors", href: basic("30-praise-opens-closed-doors") },
  { n: 31, title: "God’s Purpose For Man", href: basic("31-gods-purpose-for-man") },
  { n: 32, title: "Humility In Jesus’ Coming To Earth", href: basic("32-humility-in-jesus-coming-to-earth") },
  { n: 33, title: "Humility In Jesus’ Earthly Life", href: basic("33-humility-in-jesus-earthly-life") },
  { n: 34, title: "Humility In Jesus’ Death", href: basic("34-humility-in-jesus-death") },
  { n: 35, title: "Jesus Overcame Sin", href: basic("35-jesus-overcame-sin") },
  { n: 36, title: "Jesus Did God’s Will", href: basic("36-jesus-did-gods-will") },
  { n: 37, title: "Jesus Valued All People", href: basic("37-jesus-valued-all-people") },
  { n: 38, title: "Jesus Valued People More Than Things", href: basic("38-jesus-valued-people-more-than-things-0") },
  { n: 39, title: "Jesus Was Unpopular", href: basic("39-jesus-was-unpopular") },
  { n: 40, title: "Jesus Obeyed The Father", href: basic("40-jesus-obeyed-the-father") },
  { n: 41, title: "Jesus’ Speech Was Always Loving", href: basic("41-jesus-speech-was-always-loving") },
  { n: 42, title: "Jesus’ Love Is Seen In His Dying", href: basic("42-jesus’-gentleness-and-goodness") },
  { n: 43, title: "Finding Security In God As A Father", href: basic("43-finding-security-in-god-as-a-father") },
  { n: 44, title: "God Can Give You Wisdom", href: basic("44-god-can-give-you-wisdom") },
  { n: 45, title: "God And Money Are Opposites", href: basic("45-god-and-money-are-opposites") },
  { n: 46, title: "The Love Of Money Is Evil", href: basic("46-the-love-of-money-is-evil") },
  { n: 47, title: "Give Back What Belongs To Others", href: basic("47-give-back-what-belongs-to-others") },
  { n: 48, title: "Giving Everything To God", href: basic("48-giving-everything-to-god") },
  { n: 49, title: "God Binds Husband And Wife Together", href: basic("49-god-binds-husband-and-wife-together") },
  { n: 50, title: "Responsibilities Of Husband And Wife", href: basic("50-responsibilities-of-husband-and-wife-0") },
  { n: 51, title: "Bringing Up Godly Children", href: basic("51-bringing-up-godly-children") },
  { n: 52, title: "Responsibilities Of Parents And Children", href: basic("52-responsibilities-of-parents-and-children") },
  { n: 53, title: "Not Praying As Hypocrites Do", href: basic("53-not-praying-as-hypocrites-do") },
  { n: 54, title: "Not Praying With Meaningless Repetition", href: basic("54-not-praying-with-meaningless-repetition") },
  { n: 55, title: "Praying Putting God First", href: basic("55-praying-putting-god-first") },
  { n: 56, title: "Praying About God’s Interests", href: basic("56-praying-about-gods-interests") },
  { n: 57, title: "Praying For Our Material Needs", href: basic("57-praying-for-our-material-needs") },
  { n: 58, title: "Praying For Our Spiritual Needs", href: basic("58-praying-for-our-spiritual-needs") },
  { n: 59, title: "Hypocrisy", href: basic("59-hypocrisy") },
  { n: 60, title: "Pride", href: basic("60-pride") },
  { n: 61, title: "Selfishness", href: basic("61-selfishness") },
  { n: 62, title: "Hatred", href: basic("62-hatred") },
  { n: 63, title: "Unbelief", href: basic("63-unbelief") },
  { n: 64, title: "Unforgiveness And Bitterness", href: basic("64-unforgiveness-and-bitterness") },
  { n: 65, title: "Lying", href: basic("65-lying") },
  { n: 66, title: "Don’t Believe Satan’s Lies", href: basic("66-dont-believe-satans-lies") },
  { n: 67, title: "Anger", href: basic("67-anger") },
  { n: 68, title: "Proving God’s Perfect Will (1)", href: basic("68-proving-gods-perfect-will-1") },
  { n: 69, title: "Proving God’s Perfect Will (2)", href: basic("69-proving-gods-perfect-will-2") },
  { n: 70, title: "Proving God’s Perfect Will (3)", href: basic("70-proving-gods-perfect-will-3") },
  { n: 71, title: "Submission To Authority", href: basic("71-submission-to-authority") },
  { n: 72, title: "God’s Plan For Those Who Have Failed", href: basic("72-gods-plan-for-those-who-have-failed") },
];

export const oldTestament: Teaching[] = [
  { n: 1, title: "Genesis 1", href: bible("genesis-1"), duration: "59m" },
  { n: 2, title: "Genesis 2", href: bible("genesis2"), duration: "57m" },
  { n: 3, title: "Genesis 3", href: bible("genesis-3"), duration: "57m" },
  { n: 4, title: "Exodus 1", href: bible("exodus1"), duration: "58m" },
  { n: 5, title: "Exodus 2", href: bible("exodus2"), duration: "52m" },
  { n: 6, title: "Leviticus", href: bible("leviticus"), duration: "59m" },
  { n: 7, title: "Numbers", href: bible("numbers"), duration: "58m" },
  { n: 8, title: "Deuteronomy", href: bible("deuteronomy"), duration: "60m" },
  { n: 9, title: "Joshua", href: bible("joshua"), duration: "58m" },
  { n: 10, title: "Judges, Ruth", href: bible("judges-ruth"), duration: "55m" },
  { n: 11, title: "1 Samuel", href: bible("1-samuel"), duration: "58m" },
  { n: 12, title: "2 Samuel", href: bible("2-samuel"), duration: "58m" },
  { n: 13, title: "1 Kings", href: bible("1-kings"), duration: "56m" },
  { n: 14, title: "2 Kings", href: bible("2-kings"), duration: "58m" },
  { n: 15, title: "1 & 2 Chronicles, Ezra", href: bible("12-chronicles-ezra"), duration: "54m" },
  { n: 16, title: "Nehemiah, Esther", href: bible("nehemiah-esther"), duration: "57m" },
  { n: 17, title: "Job 1", href: bible("job1"), duration: "58m" },
  { n: 18, title: "Job 2", href: bible("job2"), duration: "55m" },
  { n: 19, title: "Psalms 1", href: bible("psalms1"), duration: "58m" },
  { n: 20, title: "Psalms 2", href: bible("psalms2"), duration: "54m" },
  { n: 21, title: "Proverbs", href: bible("proverbs"), duration: "58m" },
  { n: 22, title: "Ecclesiastes", href: bible("ecclesiastes"), duration: "57m" },
  { n: 23, title: "Song of Solomon", href: bible("song-of-solomon"), duration: "56m" },
  { n: 24, title: "Isaiah 1", href: bible("isaiah1"), duration: "57m" },
  { n: 25, title: "Isaiah 2", href: bible("isaiah2"), duration: "56m" },
  { n: 26, title: "Jeremiah & Lamentations", href: bible("jeremiah-lamentations"), duration: "56m" },
  { n: 27, title: "Ezekiel", href: bible("ezekial"), duration: "58m" },
  { n: 28, title: "Daniel", href: bible("daniel"), duration: "56m" },
  { n: 29, title: "Hosea, Joel", href: bible("hosea-joel"), duration: "54m" },
  { n: 30, title: "Amos, Obadiah", href: bible("amos-obadiah"), duration: "52m" },
  { n: 31, title: "Jonah, Micah", href: bible("jonah-micah"), duration: "55m" },
  { n: 32, title: "Nahum, Habakkuk", href: bible("nahum-habakkuk"), duration: "56m" },
  { n: 33, title: "Zephaniah, Haggai", href: bible("zephaniah-haggai"), duration: "56m" },
  { n: 34, title: "Zechariah", href: bible("zechariah"), duration: "58m" },
  { n: 35, title: "Malachi", href: bible("malachi"), duration: "54m" },
];

export const newTestament: Teaching[] = [
  { n: 36, title: "Matthew 1", href: bible("matthew1"), duration: "56m" },
  { n: 37, title: "Matthew 2", href: bible("matthew2"), duration: "59m" },
  { n: 38, title: "Mark", href: bible("mark"), duration: "58m" },
  { n: 39, title: "Luke 1", href: bible("luke1"), duration: "58m" },
  { n: 40, title: "Luke 2", href: bible("luke2"), duration: "57m" },
  { n: 41, title: "Luke 3", href: bible("luke3"), duration: "59m" },
  { n: 42, title: "John 1", href: bible("john1"), duration: "59m" },
  { n: 43, title: "John 2", href: bible("john2"), duration: "58m" },
  { n: 44, title: "Acts 1", href: bible("acts1"), duration: "58m" },
  { n: 45, title: "Acts 2", href: bible("acts2"), duration: "55m" },
  { n: 46, title: "Romans 1", href: bible("romans1"), duration: "55m" },
  { n: 47, title: "Romans 2", href: bible("romans2"), duration: "56m" },
  { n: 48, title: "1 Corinthians 1", href: bible("1-corinthians1"), duration: "57m" },
  { n: 49, title: "1 Corinthians 2", href: bible("1-corinthians2"), duration: "58m" },
  { n: 50, title: "2 Corinthians 1", href: bible("2-corinthians1"), duration: "55m" },
  { n: 51, title: "2 Corinthians 2", href: bible("2-corinthians2"), duration: "58m" },
  { n: 52, title: "Galatians", href: bible("galatians"), duration: "57m" },
  { n: 53, title: "Ephesians 1", href: bible("ephesians1"), duration: "56m" },
  { n: 54, title: "Ephesians 2", href: bible("ephesians2"), duration: "56m" },
  { n: 55, title: "Philippians", href: bible("philippians"), duration: "55m" },
  { n: 56, title: "Colossians", href: bible("colossians"), duration: "55m" },
  { n: 57, title: "1 & 2 Thessalonians", href: bible("1-2-thessalonians"), duration: "57m" },
  { n: 58, title: "1 Timothy", href: bible("1-timothy"), duration: "57m" },
  { n: 59, title: "2 Timothy", href: bible("2-timothy"), duration: "57m" },
  { n: 60, title: "Titus, Philemon", href: bible("titus-philemon"), duration: "56m" },
  { n: 61, title: "Hebrews 1", href: bible("hebrews1"), duration: "57m" },
  { n: 62, title: "Hebrews 2", href: bible("hebrews2"), duration: "57m" },
  { n: 63, title: "Hebrews 3", href: bible("hebrews3"), duration: "56m" },
  { n: 64, title: "Hebrews 4", href: bible("hebrews4"), duration: "55m" },
  { n: 65, title: "James", href: bible("james"), duration: "55m" },
  { n: 66, title: "1 Peter & 2 Peter", href: bible("1-peter-2-peter"), duration: "56m" },
  { n: 67, title: "1 John", href: bible("1-john"), duration: "57m" },
  { n: 68, title: "2 John, 3 John, Jude", href: bible("2-john-3-john-jude"), duration: "54m" },
  { n: 69, title: "Revelation 1", href: bible("revelation1"), duration: "58m" },
  { n: 70, title: "Revelation 2", href: bible("revelation2"), duration: "53m" },
];
